#include <iostream>
#include <cstdlib>
#include <ctime>
#include <vector>
#include <cctype>
#include <algorithm>

const vector <string> VALIDATION = {"Cool","Great","Perfect","Beautiful","Aw, yeah"};

int main(){
  string input;
  int pick;

  srand(time(0));
  pick = rand() % VALIDATION.size();
  cout << "What are you listening to?\n";
  getline(cin,input);
  transform(input.begin(), input.end(), input.begin(), [](unsigned char c){ return std::tolower(c); });
  cout << VALIDATION[pick] << "! Let's listen to more\n" << endl;
  input = get_input_in_lowercase();
  cout << VALIDATION[pick] << "! Let's listen to more\n";

  do{
    cout << "What's next?\n";
    input = get_input_in_lowercase();
    pick = rand() % VALIDATION.size();
    cout << VALIDATION[pick] << "!\n" << endl;
  }while( input != "nothing" );

  return 0;
}


